// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package model

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *Event) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	if z.Sources == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "sources"
			o = append(o, 0xa7, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.Sources)))
			for za0001 := range z.Sources {
				o, err = z.Sources[za0001].MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "Sources", za0001)
					return
				}
			}
		}
		// string "vulnerabilities"
		o = append(o, 0xaf, 0x76, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73)
		o = msgp.AppendArrayHeader(o, uint32(len(z.Vulnerabilities)))
		for za0002 := range z.Vulnerabilities {
			o, err = z.Vulnerabilities[za0002].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Vulnerabilities", za0002)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Event) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "sources":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sources")
				return
			}
			if cap(z.Sources) >= int(zb0002) {
				z.Sources = (z.Sources)[:zb0002]
			} else {
				z.Sources = make([]Source, zb0002)
			}
			for za0001 := range z.Sources {
				bts, err = z.Sources[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Sources", za0001)
					return
				}
			}
		case "vulnerabilities":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Vulnerabilities")
				return
			}
			if cap(z.Vulnerabilities) >= int(zb0003) {
				z.Vulnerabilities = (z.Vulnerabilities)[:zb0003]
			} else {
				z.Vulnerabilities = make([]Vulnerability, zb0003)
			}
			for za0002 := range z.Vulnerabilities {
				bts, err = z.Vulnerabilities[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Vulnerabilities", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Event) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Sources {
		s += z.Sources[za0001].Msgsize()
	}
	s += 16 + msgp.ArrayHeaderSize
	for za0002 := range z.Vulnerabilities {
		s += z.Vulnerabilities[za0002].Msgsize()
	}
	return
}
