// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package model

import (
	"github.com/DataDog/dd-iast-go/internal/model/constants"
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *Evidence) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(5)
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	if z.Value == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Pattern == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Redacted == false {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Truncated.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.ValueParts == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "value"
			o = append(o, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
			o = msgp.AppendString(o, z.Value)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "pattern"
			o = append(o, 0xa7, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e)
			o = msgp.AppendString(o, z.Pattern)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "redacted"
			o = append(o, 0xa8, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64)
			o = msgp.AppendBool(o, z.Redacted)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "truncated"
			o = append(o, 0xa9, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64)
			o, err = z.Truncated.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Truncated")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "valueParts"
			o = append(o, 0xaa, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.ValueParts)))
			for za0001 := range z.ValueParts {
				o, err = z.ValueParts[za0001].MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "ValueParts", za0001)
					return
				}
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Evidence) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "value":
			z.Value, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "pattern":
			z.Pattern, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Pattern")
				return
			}
		case "redacted":
			z.Redacted, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Redacted")
				return
			}
		case "truncated":
			bts, err = z.Truncated.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Truncated")
				return
			}
		case "valueParts":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ValueParts")
				return
			}
			if cap(z.ValueParts) >= int(zb0002) {
				z.ValueParts = (z.ValueParts)[:zb0002]
			} else {
				z.ValueParts = make([]ValuePart, zb0002)
			}
			for za0001 := range z.ValueParts {
				bts, err = z.ValueParts[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "ValueParts", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Evidence) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Value) + 8 + msgp.StringPrefixSize + len(z.Pattern) + 9 + msgp.BoolSize + 10 + z.Truncated.Msgsize() + 11 + msgp.ArrayHeaderSize
	for za0001 := range z.ValueParts {
		s += z.ValueParts[za0001].Msgsize()
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ValuePart) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(6)
	var zb0001Mask uint8 /* 6 bits */
	_ = zb0001Mask
	if z.Value == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Pattern == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Redacted == false {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Truncated.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.SourceIndex == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.SecureMarks == nil {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "value"
			o = append(o, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
			o = msgp.AppendString(o, z.Value)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "pattern"
			o = append(o, 0xa7, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e)
			o = msgp.AppendString(o, z.Pattern)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "redacted"
			o = append(o, 0xa8, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64)
			o = msgp.AppendBool(o, z.Redacted)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "truncated"
			o = append(o, 0xa9, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64)
			o, err = z.Truncated.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Truncated")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "source"
			o = append(o, 0xa6, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65)
			if z.SourceIndex == nil {
				o = msgp.AppendNil(o)
			} else {
				o = msgp.AppendInt(o, *z.SourceIndex)
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "secure_marks"
			o = append(o, 0xac, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.SecureMarks)))
			for za0001 := range z.SecureMarks {
				o, err = z.SecureMarks[za0001].MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "SecureMarks", za0001)
					return
				}
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ValuePart) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "value":
			z.Value, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "pattern":
			z.Pattern, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Pattern")
				return
			}
		case "redacted":
			z.Redacted, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Redacted")
				return
			}
		case "truncated":
			bts, err = z.Truncated.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Truncated")
				return
			}
		case "source":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.SourceIndex = nil
			} else {
				if z.SourceIndex == nil {
					z.SourceIndex = new(int)
				}
				*z.SourceIndex, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SourceIndex")
					return
				}
			}
		case "secure_marks":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SecureMarks")
				return
			}
			if cap(z.SecureMarks) >= int(zb0002) {
				z.SecureMarks = (z.SecureMarks)[:zb0002]
			} else {
				z.SecureMarks = make([]constants.VulnerabilityType, zb0002)
			}
			for za0001 := range z.SecureMarks {
				bts, err = z.SecureMarks[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "SecureMarks", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ValuePart) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Value) + 8 + msgp.StringPrefixSize + len(z.Pattern) + 9 + msgp.BoolSize + 10 + z.Truncated.Msgsize() + 7
	if z.SourceIndex == nil {
		s += msgp.NilSize
	} else {
		s += msgp.IntSize
	}
	s += 13 + msgp.ArrayHeaderSize
	for za0001 := range z.SecureMarks {
		s += z.SecureMarks[za0001].Msgsize()
	}
	return
}
