// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package model

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *Location) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(6)
	var zb0001Mask uint8 /* 6 bits */
	_ = zb0001Mask
	if z.Path == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Class == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Line == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Method == "" {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.StackID == "" {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "spanId"
		o = append(o, 0xa6, 0x73, 0x70, 0x61, 0x6e, 0x49, 0x64)
		o = msgp.AppendUint64(o, z.SpanID)
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "path"
			o = append(o, 0xa4, 0x70, 0x61, 0x74, 0x68)
			o = msgp.AppendString(o, z.Path)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "class"
			o = append(o, 0xa5, 0x63, 0x6c, 0x61, 0x73, 0x73)
			o = msgp.AppendString(o, z.Class)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "line"
			o = append(o, 0xa4, 0x6c, 0x69, 0x6e, 0x65)
			o = msgp.AppendInt(o, z.Line)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "method"
			o = append(o, 0xa6, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64)
			o = msgp.AppendString(o, z.Method)
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "stackId"
			o = append(o, 0xa7, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x64)
			o = msgp.AppendString(o, z.StackID)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Location) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "spanId":
			z.SpanID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SpanID")
				return
			}
		case "path":
			z.Path, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		case "class":
			z.Class, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Class")
				return
			}
		case "line":
			z.Line, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Line")
				return
			}
		case "method":
			z.Method, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Method")
				return
			}
		case "stackId":
			z.StackID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StackID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Location) Msgsize() (s int) {
	s = 1 + 7 + msgp.Uint64Size + 5 + msgp.StringPrefixSize + len(z.Path) + 6 + msgp.StringPrefixSize + len(z.Class) + 5 + msgp.IntSize + 7 + msgp.StringPrefixSize + len(z.Method) + 8 + msgp.StringPrefixSize + len(z.StackID)
	return
}
