// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package model

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *Source) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(6)
	var zb0001Mask uint8 /* 6 bits */
	_ = zb0001Mask
	if z.Name == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Value == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Pattern == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Redacted == false {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Truncated.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "origin"
		o = append(o, 0xa6, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e)
		o, err = z.Origin.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Origin")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "name"
			o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
			o = msgp.AppendString(o, z.Name)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "value"
			o = append(o, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
			o = msgp.AppendString(o, z.Value)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "pattern"
			o = append(o, 0xa7, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e)
			o = msgp.AppendString(o, z.Pattern)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "redacted"
			o = append(o, 0xa8, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64)
			o = msgp.AppendBool(o, z.Redacted)
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "truncated"
			o = append(o, 0xa9, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64)
			o, err = z.Truncated.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Truncated")
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Source) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "origin":
			bts, err = z.Origin.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Origin")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "value":
			z.Value, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "pattern":
			z.Pattern, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Pattern")
				return
			}
		case "redacted":
			z.Redacted, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Redacted")
				return
			}
		case "truncated":
			bts, err = z.Truncated.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Truncated")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Source) Msgsize() (s int) {
	s = 1 + 7 + z.Origin.Msgsize() + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.StringPrefixSize + len(z.Value) + 8 + msgp.StringPrefixSize + len(z.Pattern) + 9 + msgp.BoolSize + 10 + z.Truncated.Msgsize()
	return
}
