// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package constants

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z Origin) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, (Origin).String(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Origin) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z), err = parseOrigin(zb0001)

		if err != nil {
			err = msgp.WrapError(err)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Origin) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len((Origin).String(z))
	return
}
